// app/api/simulator/promo-redeem/route.ts
// Redeems a single-use promo code for a credit to the trading balance
// (artifacts/{appId}/users/{uid}/simulator/state.balance — the practice
// money, not the legacy `coins` gating currency).
//
// Codes are generated by app/api/admin/promo-codes/route.ts as
// promo_codes/{CODE} documents. firestore.rules gives the client zero read
// or write access to that collection, so this route and the admin one are
// the only paths that ever touch it.
//
// The whole "single-use" guarantee lives in one Firestore transaction below:
// the code's status is read and flipped to 'used' in the same transaction
// that credits the balance, so two redemption attempts on the same code
// racing each other can only ever have one winner — Firestore's optimistic
// concurrency serializes the losing attempt into a retry that then sees
// status: 'used' and is rejected. A separate "check, then later write" pair
// of calls (the shape the pre-existing welcome-bonus grant used) does not
// have this guarantee.
//
// Per-account limit: one promo redemption ever, tracked as
// users/{uid}.promoCodeRedeemedAt — a protected field firestore.rules
// excludes from client writes, checked in the SAME transaction so a user
// can't redeem two different codes by racing two requests either.

import { NextRequest, NextResponse } from 'next/server';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import { moneyAdd, roundMoney } from '@/lib/utils/money';
import { checkPersistentRateLimit } from '@/lib/utils/persistentRateLimit';

// Ensure Firebase Admin is initialized with full credentials
import '@/lib/coinManagerServer';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// 5 attempts per minute per uid — generous enough for any real user
// (one attempt is all you need if your code is right), tight enough to
// stop a script guessing random codes and paying for the Firestore reads.
const REDEEM_MAX_ATTEMPTS = 5;
const REDEEM_WINDOW_MS = 60_000;

// Matches app/api/simulator/trade/route.ts's SANE_BALANCE_CAP. Admin SDK
// writes bypass firestore.rules entirely, so every privileged balance
// writer has to re-enforce this cap by hand — see that file's comment.
const SANE_BALANCE_CAP = 100_000_000;

type RedeemFailure =
  | 'ALREADY_REDEEMED_BY_USER'
  | 'INVALID_CODE'
  | 'CODE_ALREADY_USED'
  | 'CODE_DISABLED'
  | 'CODE_EXPIRED'
  | 'BALANCE_CAP';

const FAILURE_RESPONSES: Record<RedeemFailure, { status: number; error: string }> = {
  ALREADY_REDEEMED_BY_USER: {
    status: 409,
    error: 'You have already redeemed a promo code — one redemption is allowed per account.',
  },
  INVALID_CODE: { status: 404, error: 'That code is not valid.' },
  CODE_ALREADY_USED: { status: 409, error: 'That code has already been used.' },
  CODE_DISABLED: { status: 409, error: 'That code is no longer active.' },
  CODE_EXPIRED: { status: 410, error: 'That code has expired.' },
  BALANCE_CAP: { status: 400, error: 'This would exceed the maximum allowed balance.' },
};

class RedeemError extends Error {
  constructor(public code: RedeemFailure) {
    super(code);
  }
}

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get('authorization') || req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ success: false, error: 'Missing or invalid Authorization header' }, { status: 401 });
    }
    const token = authHeader.substring(7).trim();

    const adminAuth = getAuth();
    let decodedToken;
    try {
      decodedToken = await adminAuth.verifyIdToken(token);
    } catch {
      return NextResponse.json({ success: false, error: 'Invalid or expired token' }, { status: 401 });
    }
    const uid = decodedToken.uid;

    // Rate-limit: 5 attempts per uid per minute. Keyed by uid so shared-IP
    // carrier-NAT (common in BD) doesn't punish unrelated users, and a single
    // account can't burn Firestore reads by cycling through guessed codes.
    const allowed = await checkPersistentRateLimit(`promo-redeem:${uid}`, {
      maxRequests: REDEEM_MAX_ATTEMPTS,
      windowMs: REDEEM_WINDOW_MS,
    });
    if (!allowed) {
      return NextResponse.json(
        { success: false, error: 'Too many attempts. Wait a minute and try again.' },
        { status: 429 }
      );
    }

    let body: any;
    try {
      body = await req.json();
    } catch {
      return NextResponse.json({ success: false, error: 'Invalid JSON body' }, { status: 400 });
    }

    const rawCode = body?.code;
    if (typeof rawCode !== 'string' || !rawCode.trim()) {
      return NextResponse.json({ success: false, error: 'Enter a promo code' }, { status: 400 });
    }
    // Same normalization the admin generator produces: uppercase, no
    // whitespace, so pasting-with-spaces or lowercase typing still matches.
    const code = rawCode.trim().toUpperCase().replace(/\s+/g, '');
    if (!/^[A-Z0-9-]{4,32}$/.test(code)) {
      return NextResponse.json({ success: false, error: 'That doesn\'t look like a valid code.' }, { status: 400 });
    }

    const db = getFirestore();
    const appId = process.env.NEXT_PUBLIC_SIMULATOR_APP_ID || 'stocksimulatorbd-dse-v1';
    const userRef = db.doc(`users/${uid}`);
    const promoRef = db.doc(`promo_codes/${code}`);
    const stateRef = db.doc(`artifacts/${appId}/users/${uid}/simulator/state`);

    let creditedAmount = 0;

    await db.runTransaction(async (transaction) => {
      const [userSnap, promoSnap, stateSnap] = await Promise.all([
        transaction.get(userRef),
        transaction.get(promoRef),
        transaction.get(stateRef),
      ]);

      if (userSnap.data()?.promoCodeRedeemedAt) {
        throw new RedeemError('ALREADY_REDEEMED_BY_USER');
      }
      if (!promoSnap.exists) {
        throw new RedeemError('INVALID_CODE');
      }

      const promo = promoSnap.data()!;
      if (promo.status === 'used') throw new RedeemError('CODE_ALREADY_USED');
      if (promo.status === 'disabled') throw new RedeemError('CODE_DISABLED');
      if (promo.status !== 'active') throw new RedeemError('INVALID_CODE'); // unrecognised status — treat as invalid, never credit
      if (typeof promo.expiresAt === 'string' && new Date(promo.expiresAt).getTime() < Date.now()) {
        throw new RedeemError('CODE_EXPIRED');
      }

      // Never trust anything about the amount except what's stored on the
      // code doc itself — there is no client input for it at all here.
      const amount = promo.amount;
      if (typeof amount !== 'number' || !Number.isFinite(amount) || amount <= 0) {
        throw new RedeemError('INVALID_CODE');
      }

      const currentBalance =
        stateSnap.exists && typeof stateSnap.data()?.balance === 'number' ? stateSnap.data()!.balance : 0;
      const newBalance = roundMoney(moneyAdd(currentBalance, amount));
      if (newBalance > SANE_BALANCE_CAP) {
        throw new RedeemError('BALANCE_CAP');
      }

      creditedAmount = amount;
      const nowIso = new Date().toISOString();

      if (stateSnap.exists) {
        transaction.update(stateRef, { balance: newBalance });
      } else {
        // Matches app/api/simulator/ensure-state/route.ts's zero-state shape.
        transaction.set(stateRef, { balance: newBalance, portfolio: [], totalInvested: 0, realizedGainLoss: 0 });
      }

      transaction.set(
        promoRef,
        { status: 'used', redeemed: true, redeemedBy: uid, redeemedAt: nowIso },
        { merge: true }
      );

      transaction.set(userRef, { promoCodeRedeemedAt: nowIso }, { merge: true });
    });

    console.log(`[promo-redeem] ✓ ${uid} redeemed ${code} for ${creditedAmount}`);

    return NextResponse.json({
      success: true,
      amount: creditedAmount,
      message: `৳${creditedAmount.toLocaleString()} added to your balance!`,
    });
  } catch (err: any) {
    if (err instanceof RedeemError) {
      const { status, error } = FAILURE_RESPONSES[err.code];
      return NextResponse.json({ success: false, error }, { status });
    }
    console.error('[promo-redeem] Failed:', err);
    return NextResponse.json({ success: false, error: 'Failed to redeem code. Please try again.' }, { status: 500 });
  }
}
